objectdict = {
    'driver_loc': 'C:\Mohesh\Drivers\chromedriver.exe',
    'given_url': 'https://www.saucedemo.com/',
    'User_name1': 'standard_user',
    'pwd1': 'secret_sauce',
    'User_name2': 'locked_out_user',
    'pwd2': 'secret_sauce',

    'username_locator': 'user-name',
    'pwd_locator': 'password',
    'login_button_locator': 'login-button',
    'Three_bar_locator': "react-burger-menu-btn",
    'About_locator': "about_sidebar_link",
    'logo_locator': "//div[@class='MuiBox-root css-lwb5go']",
    'invalid_user_error': "//h3[contains(text(),'locked out')]",
    'filter_locator': "//select[@class='product_sort_container']",
    'low_price_product': "(//div[@class='inventory_item_name'])[1]",
    'add_to_cart_locator': 'add-to-cart-sauce-labs-onesie',
    'cart_logo_locator': 'shopping_cart_container',
    'checkout_button_lcator': 'checkout',
    'checkout_first_name_locator': 'first-name',
    'checkout_last_name_locator': 'last-name',
    'checkout_zip_locator': 'postal-code',
    'continue_button_locator': 'continue',
    'checkout_total': "//div[@class='summary_info_label summary_total_label']",
    'finish_button_locator':"finish",
    'checckout_complete_page_text':"//h2[contains(text(),'Thank')]",
}
